name: "Python Poetry Action"
description: "An action to setup Poetry"
inputs:
  working-directory:
    description: "Working directory for the steps"
    required: true
  python-version:
    description: "Version of Python to use"
    required: true
  install-dependencies:
    description: "Whether to install dependencies"
    required: false
    default: "true"
  install-package:
    description: "Whether to install the package"
    required: false
    default: "true"
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Set up Poetry
      run: |
        pip install --user pipx
        pipx ensurepath
        pipx install poetry
      shell: bash

    - name: Get full Python version
      id: full-python-version
      shell: bash
      run:
        echo "full_version=$(python -c 'import sys; print(".".join(map(str,
        sys.version_info[:3])))')" >> $GITHUB_OUTPUT

    - name: Cache Poetry
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      with:
        path: ~/.cache/pypoetry
        key:
          ${{ runner.os }}-poetry-${{ hashFiles(format('{0}/poetry.lock',
          inputs.working-directory)) }}-${{
          steps.full-python-version.outputs.full_version }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install Dependencies
      if: ${{ inputs.install-dependencies == 'true' }}
      run: |
        poetry install --no-root --no-interaction
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Install Package
      if: ${{ inputs.install-package == 'true' }}
      run: |
        poetry install --no-interaction
      shell: bash
      working-directory: ${{ inputs.working-directory }}
